### ISSUE TITLE
Feature Request: Implement Common Vendors / Software

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#101]
This will allow you to globally change vendor info and link vendors and software to clients

**Comment by johnnyq** [comment]
decided not to add this really wont help any

**Comment by johnnyq** [comment]
Reopening this can be extremely useful

**Comment by johnnyq** [comment]
This is very much needed just not 100% the best way to implement this one

**Comment by wrongecho** [comment]
Hey @johnnyq, is this feature about having "global" or "roaming" vendors? I like the idea of having vendors that are specific to clients but also the ability for a vendor to be associated with multiple clients.

Found a request on the forum too: https://forum.itflow.org/d/69-roaming-vendors

**Comment by johnnyq** [comment]
Vendor Templates have been implemented see here
67a9a484afcb05b3af119cfc5b8adf2057a7af75

**Comment by johnnyq** [comment]
Software templates are now implemented

b3f952b1f80a048e5830d5ac2b70b7a93140d2d0

**Comment by johnnyq** [comment]
Closing
