### ISSUE TITLE
Feature Request: Convert logging to a function

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#1039]
If we convert logging to a function, we can save on a lot of repetition, e.g.
- mysqli_query($mysqli,"INSERT INTO logs SET log_type
-  log_ip = '$session_ip', log_user_agent = '$session_user_agent',
- log_user_id = $session_user_id,

---

Something like
logAction( type , action , description , client_id (nullable) , entity_id (nullable) )

Would convert the below:
`mysqli_query($mysqli,"INSERT INTO logs SET log_type = 'Interface', log_action = 'Delete', log_description = '$session_name deleted interface $interface_name from asset $asset_name', log_ip = '$session_ip', log_user_agent = '$session_user_agent', log_client_id = $client_id, log_user_id = $session_user_id, log_entity_id = $asset_id");`

into:
`logAction('Interface', 'Delete', '$session_name deleted interface $interface_name from asset $asset_name', $client_id, $asset_id`);

**Comment by johnnyq** [comment]
Hey @wrongecho this would be fantastic totally up for this

**Comment by johnnyq** [comment]
logging as been fictionalized, working slowly to implement everywhere https://github.com/itflow-org/itflow/commit/7b4dda0ad612de9cbcc89fe6625195df9f243c38

closing out
