### ISSUE TITLE
Feature Request: Add asset button Global Assets and SSL Cert

### ISSUE THREAD

**Issue by aftechro** [itflow-org/itflow#131]
Hello, 

How can i add assets? the ADD Asset button missing.

Also, from where can i change the Location when i set it up as a fresh. it has only US and Canada.
Where can i change the dollars to euro for instance?

Thank you!

**Comment by johnnyq** [comment]
Hi @afsound. Add a client then click on the client then click assets you will be able to add assets that way for now. The add asset feature will soon come to global assets.

Currently we haven't implemented all the localization as we wanted yet but is planned.

**Comment by afsound** [comment]
Hi Johny, 

Thanks very much for it.  That works fine. I`m happy with it to have it on client asset section. But yeah, global asset will be nice.


Please see in line:

1. How can i add another filed as url on login section of the assets.

So basically, on the assets if i want to add just passwords of hosting service, admin emails of office365, gsuite admin etc... or can you make a section of passwords, like IT Glue have?

![image](https://user-images.githubusercontent.com/38830718/105626176-22c47280-5e26-11eb-8395-f30d162e297f.png)
![image](https://user-images.githubusercontent.com/38830718/105626380-1ee52000-5e27-11eb-8771-5a4bf6dd24f5.png)



2. Some other options would be great to have them

**Documentation** - where you can add certain type of instructions for particular client if needed.
For instance, how to access and setup the VPN and so on.

What about **Configuration** tab as

![image](https://user-images.githubusercontent.com/38830718/105626300-ab431300-5e26-11eb-9ee7-fe68c61928ee.png)

**SSL Tracker**
![image](https://user-images.githubusercontent.com/38830718/105626328-daf21b00-5e26-11eb-8eda-18de2a8f1630.png)


So far i`m very happy with the system, is just that would be nice to have some handy features on next updates maybe :P


3. Regarding the tickets, would they will show up if a customer will send an email to the registered email in email section? (like email piping?) 
Or it has to be open manually each time? 

Didnt test the feature yet, but i was just curious how this will work.

Thank you in advance!

**Comment by afsound** [comment]
Oh, forgot a thing,

Can there will bee global vendor? For instance, if i`m using same vendors for webhosting, email and so on... better to have them as global, then have to add date for each client.

**Comment by johnnyq** [comment]
Hi @afsound 
    Thank you for the detailed information! To answer your questions:

1. Documentation pieces should go into the notes section under the client profile. 
    Good Idea on SSL Tracker I will implement this one.
2. Email Piping is a great idea as well, i'll look into implementing it after 1.0 release. Currently tickets have to be opened manually.

**Comment by johnnyq** [comment]
@afsound I actually was going to implement global vendors except i went against it, although what your saying makes alot of sense. Im going to reopen that issue and start working on it.

**Comment by afsound** [comment]
Cool, will wait for the next update then!
Thank you!

**Comment by johnnyq** [comment]
Keeping this open for tracking will close once implemented

**Comment by johnnyq** [comment]
Added Certificate @afsound let me know if this looks good on your end

4fec4dd36bc9d30cec894309d908a942f8a98287

**Comment by afsound** [comment]
Looks good! and it`s a start :D

Any chance the SSL will be grabbed from the domain and fill in the date automatically?  Probably with future updates

here is the IT Glue example

![image](https://user-images.githubusercontent.com/38830718/105915453-a8634080-6027-11eb-8fa5-2d0dc2da8c1e.png)

and this is the results data, with attachements (for crt,pfx,key files) and related items
![image](https://user-images.githubusercontent.com/38830718/105915652-dd6f9300-6027-11eb-8392-a8676eadd95a.png)

**Comment by johnnyq** [comment]
I think I can accomplish that, ill probably do the same with domains as well. Keep them coming you are providing excellent information
