### ISSUE TITLE
Feature Request: Seperate Dashboards (Tech - Accounting/Sales)

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#141]
**Tech**

- Ticket Metrics
- Recently updated clients

**Accounting**
- Sales Metrics

**Comment by wrongecho** [comment]
Some thoughts:
- Separate dashboards should be shown/redirected depending on your role
- Dashboards should take into account any disabled modules, and hide metrics/stats for these

**Comment by johnnyq** [comment]
This has been done
