### ISSUE TITLE
Rename Entities

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#151]
Rename the following

- Software > Licenses
- Logins > Passwords
- Assets > Devices

Including DB info

**Comment by johnnyq** [comment]
Feedback on this, Is this a good idea or should I just leave it alone?

**Comment by gwes** [comment]
My $0.02 worth would be that the suggested renames make the items more specific which might not be a good thing.

For software you might want edition, version, update url, license type, license renewal, licence key. Not just license
I might not just want to store passwords but username, password, TOTP key, pw change URL
Devices is a subset of assets, struggling with an example right now.

So, if you are just changing the name but not what information you are storing then does it matter? I've not looked at that bit of the system yet to know what's in those bits.

**Comment by johnnyq** [comment]
Good Ideas, ill implement the software fields

**Comment by aftechro** [comment]
I would leave the Software, Passwords and Configurations
