### ISSUE TITLE
Good Defaults Thoughts

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#158]
### Expenses

- Office Supplies
- Travel
- Advertising or Marketing?
- Professional Service

### Income

- Service
- Product

### Referrals

- Google
- Friend
- Craigslist
- Facebook
- Sign
- Other

Any Thoughts?

**Comment by gwes** [comment]
"generic *" or maybe "uncategorised *" or "general *".
So you have a default place to put stuff if it does not match an existing category but you CBA to make a new one. For example for when you get a refund from a supplier but they don't issue a credit note and you just need to record it somewhere as an income (might not be the best example)

If you look at something like Sage or quickbooks or Xero or the like they all have loads and loads of options and I always struggle to remember what goes where. Keeping it simple is probably half the battle and let people make their own.

My current setup (quickbooks online) I use the following most of the time;
(none exhaustive list)

Income
Uncategorised Income, Hardware Sales, 3rd Party Software Sales , Software Sales, Web Hosting Sales, Labour (probably a few others)

Expenses
Hardware Internal, Software Internal, Subscriptions, Services (Lawyers, Accountant, etc), Office related, Travel, Marketing

Cost of sales (Expenses directly linked to sales)
Uncategorised CoS, Hardware Purchases, 3rd Party Software Purchases, Web Hosting Purchases, 3rd party Labour 

It's easy to get carried away though but I always try and look at it from the other end.... What am I likely to want to see separated out in the future. Anything you might need to easily group you will need a category for.

**Comment by aftechro** [comment]
I suppose these expenses refers to IT Company as the expenses of the services/product for the client


**Expenses:**
yours plus below
**Hardware** (pc, laptop, accessories, cables, patches and so on...) Main category Hardware, sub-cat user can input type of hardware
**Software** (Licenses (Office365, Windows, Adobe etc) - Direct cost of licenses from reseller or provider - without the margin added to customer)
**Backup services** - Online backup service that`s paid for the customer 

- I would also split these in 2 parts: monthly and early for easier tracking and programming with the invoicing part
- add a filed of margin to the final cost

eg columns: **Category (dropdown) - Sub-cat (user input) - purchase cost - margin - total purchase + margin**

then this will reflect to the final invoice


hope this make sense, i dont know how best to put it :D 

**INCOME**
- Product
- Service
- Maintenance support (for the monthly clients who paying the monthly support contract - fixed term contract of 12 month for 80 Euro/month) 
- Remote support ( this is for the one off charge of the clients who dont have monthly contract but they need remote or call out support - eg. remote 50 euro/hour call out 100 euro/hour)
- Referrals (or the right naming) - the percent of the referrals income from different services that are re-sold trough the IT Company eg: for any customer that uses 3rd party service, the 3rd party company will pay some percentage. 
For instance, voip phone company pays 10% month of the customer bill, the VPS provider, give me another 5% per month for each customer

again, here just need to find the right naming for the type of the expenses and income
