### ISSUE TITLE
Feature Request: Add Tax Collected to Reports

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#159]
Add Tax Collected Report similar to income or expense report. This is so taxes can be done properly at the end of the quarter

**Comment by gwes** [comment]
In the UK if you are "registered for VAT" you need total sales, VAT charged on sales, total purchases, VAT charged on purchases. You can then opt to send in your "return" on a monthly, quarterly or yearly basis.

Depending on how you are registered the "totals" might be either on the total of invoices generated / received (Standard accounting) OR on the payments you have made and received (Cash Accounting)

Not sure if it would be possible to include that sort of information or if that's the same for you guys in the US or not?

**Comment by johnnyq** [comment]
Complete Closing
