### ISSUE TITLE
Feature request: Restore from database backup

### ISSUE THREAD

**Issue by Shootify** [itflow-org/itflow#170]
Hi Johnny, to keep up with the **current** updates, what would be the right method to backup and restore ? phpmyadmin? in the future 1.0 release a Backup and restore build in would be nice. thanks and keep it  up

**Comment by johnnyq** [comment]
Hi @Shootify I agree, and we plan on having that functionality as well as export / import records via CSV. Currently ITFlow is going through many structural changes which causes previous versions to break. We are working on solidifying the core, and hope to have 1.0 out the door within a few months.

**Comment by aftechro** [comment]
can we integrate https://www.adminer.org/ just php based db admin, no phpmyadmin needed :D 
works like domain/sql.php

**Comment by johnnyq** [comment]
hello @aftechro we do not plan on including adminer directly into our project however as you may know adminer can be downloaded separately and it can be installed in a sub directory of itflow. Just login with the itflows DB user and password.

**Comment by wrongecho** [comment]
In terms of upgrading, you'll be able to see differences between your current DB structure and the latest from db.sql.
Database backups (manual & automated) are now implemented.

I'm not aware of a plan for restoring yet (aside from just loading the exports/backups into the database via phpMyAdmin). Will leave this open.

**Comment by johnnyq** [comment]
Closing as Backups and Restore should be handled by a backup application not ITFlow itself.
