### ISSUE TITLE
Feature Request - Tree Level Document Support

### ISSUE THREAD

**Issue by randysrs** [itflow-org/itflow#174]
any roadmap ? need a howto/general KB folder at the top level . i get you have a document folder in each client which is cool , but would like to have a option for a tree level

my thought process is we have 50 +documents from LOB/SOP docs, would like to organize them by folders , rather then search 50 docs for those .
thoughts

example of structure

Client Docs

Employee documents
    LOB documents
    General Howtos

upper level Document / KB area would be above all Clients 

Document/KB Area
   Linux Howtos
   Windows Howtos
   General Howtos

function to create additional folder structure
can someone give me some pointers where i can learn more about write that extra code 

Thanks 
Randy

**Comment by johnnyq** [comment]
@randysrs Good idea, but no real roadmap or docs as of yet. Unfortunately i've been quite busy running my MSP lately and has caused me to step back on development on the ITFlow. Looking forward to getting back into to the flow.

**Comment by wrongecho** [comment]
You can now organise documents into folders.

![image](https://user-images.githubusercontent.com/32306651/208251965-e412aa4c-e920-496a-8674-b7622b3beaac.png)

**Comment by johnnyq** [comment]
Complete closing
