### ISSUE TITLE
FEATURE REQUEST - Client Prints

### ISSUE THREAD

**Issue by Malcharias25** [itflow-org/itflow#178]
@johnnyq I love the fact that you've implemented the ability to print out a report on all client configurations, but I think it would be more helpful if there was an option on the Print page to include/exclude some data. For instance, if I'm generating an asset report for a client, I'd like to be able to include the assets and software licenses, but perhaps not the documents or passwords.

Is this something that could be easily implemented?

**Comment by johnnyq** [comment]
Actually that's a good idea @Malcharias25 , we can have little check marks next to the index to each that show/hide sections like passwords, etc. This shouldn't be hard to implement at all, ill get to it.
