### ISSUE TITLE
Feature Request: Deleting/archiving records should prompt for confirmation

### ISSUE THREAD

**Issue by Malcharias25** [itflow-org/itflow#181]
I consider this a bit of a bug, but perhaps it fits better as a feature request... I'll leave that to you to decide.

I would like to see a feature implemented where, when someone clicks the Delete option in any menu (client records, documents, assets, etc.) they get a prompt asking to confirm the action - perhaps with a check box or the like. This will help reduce the chances of accidental deletion of records (which I've had happen a couple of times already as I've been inputting information!)

Additionally, it would be nice if there was a user role that had read-only access to the data - this could be used to give clients logins to their specific records, for instance.

**Comment by johnnyq** [comment]
Yeah I must admit @Malcharias25  I have done the same, ill go ahead and implement this feature

**Comment by johnnyq** [comment]
This is complete closing
