### ISSUE TITLE
Feature: Client Tags

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#190]
This feature will allow you to add multiple tags to your clients which will be searchable. This will in turn will expand / replace the Support Field Maintenance and non-Maintenance which will be tagged feature. Common Tags could include Maintenance, non-Maintenance, Web Hosting, Network monitoring etc. These tags can be customizable

**Comment by johnnyq** [comment]
DB Structure Added

**Comment by johnnyq** [comment]
d23d455cd9ee9c86c3e16ceb0d1f318e95620806

**Comment by johnnyq** [comment]
still need to be able to search client tags within the client listing not sure the best way to implement this. Also Display up to three tags and add a line break so tags don't run off

**Comment by wrongecho** [comment]
Related to #346

**Comment by johnnyq** [comment]
closing this one as client tags are complete
