### ISSUE TITLE
Feature: Mailing List / Mass Mail

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#191]
This feature will allow you to send out mass mail to clients based off the client tag feature that we will introduce. This can be helpful  if you want to send a mass email to all Web hosting clients to remind them of a maintenance or if you want to inform everyone in the non-maintenance category why it would be a good idea to get on a proactive maintenance MSP plan etc.

**Comment by aftechro** [comment]
Well thinking and very handy to have it! Thank you!

**Comment by johnnyq** [comment]
f939ca41aac5972e1fc96d68b8ab5225d8c48961

**Comment by wrongecho** [comment]
This was removed again via 14953fe171fe0cb1439bff92eced568dbc65e85a
