### ISSUE TITLE
Feature: Multi-select - Edit / Archive / Delete multiple records at once

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#192]
The Ability to modify many records at once same with edit and delete

https://forum.itflow.org/d/440-feature-request-multi-select-edit-archive-delete-multiple-records-at-once

**Comment by wrongecho** [comment]
Need this for ticketing too! (#225)

**Comment by wrongecho** [comment]
@johnnyq - Are we safe to close this now?
