### ISSUE TITLE
Feature request: Credit to customer

### ISSUE THREAD

**Issue by aftechro** [itflow-org/itflow#193]
Hey @johnnyq,

Hope you are doing well!

Would you mind to add a credit option that can be added to the client and to be shown both under client`s dashboard underneath on Billing section as well on the main dashboard as a new card which will calculate the total of income/expenses,profit and credit? 

on another note,

For some reason i cannot access your demo url, neither mine, which both using same credentials demo@demo and pass: demo. Strange though, we both having same issue :))

**Comment by johnnyq** [comment]
Good Request I just had a client ask to buy time so a credit feature would come in great handy there I will implement this.

Demo has been fixed and is currently on the latest release I think the old demo was like 8 months old

Thanks for reporting.

**Comment by o-psi** [comment]
My code was getting a bit stale and I do not have time to tackle this right now. Leaving where I left off here incase anyone wants to pick up.

https://github.com/itflow-org/itflow/commit/38528ebb656db2a2bb7e01cd1e6c9d464787bd93

**Comment by wrongecho** [comment]
@johnnyq - Closing per our discussion. We have invoice discounts now, we can add credits if there is substantial interest, but many use cases are covered.
