### ISSUE TITLE
Feature Request: Ability To Set Idle Timeout

### ISSUE THREAD

**Issue by athornfam2** [itflow-org/itflow#223]
Wanted to request an option to allow each user or by global policy an idle timeout policy. I feel the current/default one is too short and it would be nice to set it based on choice.

**Comment by johnnyq** [comment]
sounds like a good idea i will implment this soon as well

**Comment by wrongecho** [comment]
We've come to the conclusion that the "idle timeout" seems to be something weird on/between the server (php garbage collection) or on the client (e.g. a browser extension). It isn't something controlled directly by ITFlow.

See: https://forum.itflow.org/d/310-time-outs-while-editing-a-document
