### ISSUE TITLE
Feature Request: Ticketing System Improvements

### ISSUE THREAD

**Issue by athornfam2** [itflow-org/itflow#225]
* Create a way to send tickets from customers through e-mail and then parse base on domain name
* Add more to reporting (Average Response and Resolution Time, Service Requests, Ticket satisfaction)
* Add a "smiley response" (customer feedback based on ticket which will eventually be stored under their customer ID)
* Candid responses
* Round-robin ticket selection
* Waiting for response/customer - responses
* Portal for customers to check on tickets
* Portal for customers to open new tickets (custom entry form)
* Mass change ticket entry (example - closing PRTG alerts)
* Ability to post internal notes - non-customer sending
* SLA plans
* Category selection based on subject or body input (keyword search)
* Daily or weekly reports to helpdesk lead/manager based on tickets that haven't received a response/been updated/stale

**Comment by johnnyq** [comment]
All good requests but have to work on most important things first keep em coming

**Comment by wrongecho** [comment]
If I could add to this just as somewhere structured to track my ideas...
- Scheduled tickets (automatically raised weekly/monthly)
- Time tracking
- Merging
- Linking tickets to a master ticket
- Different ticket views/filters (e.g. my tickets, unassigned tickets, my team's tickets)
- Ticket types: incident/service request

**Comment by athornfam2** [comment]
@wrongecho check out ticket #221

**Comment by wrongecho** [comment]
@athornfam2, thanks for pointing that out!

**Comment by wrongecho** [comment]
Moved to https://forum.itflow.org/d/441-moved-from-github-issues-feature-request-ticketing-system-improvements-225
