### ISSUE TITLE
Feature Request: Asset Management

### ISSUE THREAD

**Issue by athornfam2** [itflow-org/itflow#227]
* Ability to duplicate assets
* Ability to quick edit
* Bulk edit existing assets (delete, change category, owner, etc)

**Comment by johnnyq** [comment]
Yes very good requests, keep them coming

**Comment by EIT-AUS** [comment]
intergration with snip-it would work well https://github.com/snipe/snipe-it

**Comment by wrongecho** [comment]
Assets can now be duplicated.

Bulk / quick editing to be covered via #192
