### ISSUE TITLE
Feature Request: Workflows

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#238]
## Workflows / Checklists
I'd like to propose a feature of "workflows". I see a workflow as a way of keeping track of checklists of things you have to complete fairly regularly in response to a ticket/service request. Workflows can be linked to a document detailing the exact procedures to complete each workflow item.

Similar to something like this: https://docs.servicenow.com/bundle/rome-platform-user-interface/page/use/using-forms/concept/c_Checklists.html

----

## Example: New User Onboarding
- You have an SOP document detailing what actions need to take place to add a new user (like making them an account, giving them licenses, etc)
- You create a workflow checklist of the high-level items of this document:-

#### * Create user in AAD & Assign licenses
Each user must have an account on the Contoso tenant.
Open the O365 Portal -> Users > Add User
Assign the user an E3 License
#### * Assign group membership
Depending on the users job function, they may need access to one or more of the following groups. Additional groups may also be specified as per the service request [....]: 
Job role: groups; etc, etc, etc.
#### * Setup laptop
All org users are issued laptops [...]. 
Load the laptop with WDS, etc, etc.

### Workflow: New Users
- Create user in AAD & assign licenses
- Assign user groups
- Setup user laptop

HR submits a new ticket requesting that a new user be created. 
Once reviewed, you associate the ticket with your New Users workflow for that particular client. You can then check off items on the workflow as you complete them, in accordance with the SOP document you were initially using.

----

I see the database structure being something like:

**table workflows**
- workflow_id, workflow_client_id (FK clients.client_id), workflow_name, workflow_desc, workflow_document_id (FK documents.document_id)
**workflow_items**
- item_id, item_workflow_id (FK workflows.workflow_id above), item_name, item_desc (maybe?)
**workflow_item_progress**
- ticket_num, workflow_id (FK above), item_id (FK workflow_items.item_id), item_status (0/1 int?)

----
### Creating workflows
- Select client
- Create SOP Document
- Create Workflow
-- Link the SOP document
-- Create individual items, (e.g. user in AAD, user groups, setup laptop)
- Additional options to update/delete workflows

### Add workflow to ticket
- Maybe like the relation tab on logins
- Relate a ticket with a workflow
-- This triggers the creation of workflow_item_progress for that ticket_id for each workflow item
- Ticket shows workflow status (e.g. x of x items complete)
-- related SOP document link
-- Somewhere would be checkboxes to mark workflow items as complete as they get completed (possibly customer visible eventually?)

Please let me know your thoughts? If we like the idea, I can probably try to implement some of this.

**Comment by johnnyq** [comment]
I think its a great idea @wrongecho although I need to fix existing bugs and make sure what was already created, functions like it should for the 1.0 release, but im deff not opposed to this. I m grateful for your contributions

**Comment by o-psi** [comment]
Looking at how I would implement, and I notice a Tasks table in the DB. Is this in use somewhere? I could not find any references.

**Comment by wrongecho** [comment]
@o-psi As far as I'm aware, it's not yet in use.

@johnnyq

**Comment by wrongecho** [comment]
Moved this issue to backlog, we'll get around to it sometime after the 1.0 release.

**Comment by o-psi** [comment]
@wrongecho While I understand this is a low priority for release, in our organization it is high priority. 

We are looking to hire an Upwork dev to help with this project. Any further assistance or input is appreciated.

**Comment by wrongecho** [comment]
Whilst it's honestly amazing you're that keen to help with ITFlow that you'd pay an Fiverr/Upwork dev, it's worth noting we've had others go down this path and it ultimately ended up as a wasted cost. The resultant code didn't follow the existing naming conventions or standards and would have been a huge pain to maintain further down the line so it was ultimately not included.

I can appreciate that this feature is important to you, but it's remained a low priority as there hasn't really been much demand for it in comparison to other features. The most people have mentioned is the ability to add ticket tasks. 

We _may_ be able to fit in very slimmed down basic tasks to tickets before the 1.0 release, but fully adding the entire workflows concept seems like a challenge.

**Comment by johnnyq** [comment]
I don't mind having an upwork dev help out as long as the same coding standards is followed like you are currently doing @o-psi We deff do not want a Fiverr guy or one of those quick fix developers that introduce whole frameworks into our code to make something so small work as @wrongecho has stated.

**Comment by o-psi** [comment]
Yessir, of course. We have used UpWork in the past for one off dev work, and there are 2 PHP devs I quite like. 

Before you see any of their work, it will run past my eyes for approvals. :)

**Comment by o-psi** [comment]
Yessir, of course. We have used UpWork in the past for one off dev work, and there are 2 PHP devs I quite like. 

Before you see any of their work, it will run past my eyes for approvals. :)

**Comment by romkslrqusz** [comment]
Not sure if this is the appropriate place to leave this comment, just thought I'd chime in to say that, from a break/fix repair shop standpoint, this functionality is essential.
This is one of the bigger things that keep ITFlow from being viable for us.

**Comment by wrongecho** [comment]
Closing - This has essentially been implemented now with Tasks, Projects & Ticket Templates.
Future work might be to allow some of these to be exposed to the client portal to create something similar to a service catalog, but we'll see if anyone is interested in that first!
