### ISSUE TITLE
Feature Request: Integrate Stripe Payment processing

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#28]
Integrate Stripe Payment processing so customers can pay with a credit card

**Comment by johnnyq** [comment]
started the payment form

**Comment by johnnyq** [comment]
Need help with this one, i'm a little rusty with javascript

**Comment by johnnyq** [comment]
We still need help on this one

**Comment by afsound** [comment]
have a look here:

https://www.itsolutionstuff.com/post/laravel-57-stripe-payment-gateway-integration-exampleexample.html

used this a a while ago and worked fine.
