### ISSUE TITLE
Logo - Color Palette - Forums - Better Website - Other Materials

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#287]
- Yes we need a logo
- Good Color Palette
- and maybe some marketing materials (Letter head stuff)
- was looking at AI generated marketing material and Logos at https://logoai.com
- Better Site (obviously logo and Palette need to come first) (Also has to be static)
- Better Forums (Discourse)

All this will help bring the project the together and bring a wider community onboard

**Comment by aftechro** [comment]
i like these ones:
1. ![image](https://user-images.githubusercontent.com/38830718/149640159-9721b4ea-8442-464d-a279-39701d59a051.png)
2. 
![image](https://user-images.githubusercontent.com/38830718/149640229-94acd0fa-2db2-4e7e-8c11-73952c48cf2b.png)

3. 
![image](https://user-images.githubusercontent.com/38830718/149640443-a5d9b5c0-29c3-4583-b0d2-f11a8b226771.png)

**Comment by johnnyq** [comment]
I like those too, the problem is I like so much Im really gonna thing on this hahaha

**Comment by johnnyq** [comment]
New Forums is up at https://forum.pittpc.com much more features than our custom basic forum.

**Comment by aftechro** [comment]
i inclining to the number 2 as logo, simple and modern in the same time. will go great as web logo and on business cards, t-shirts and so on :d what you think?

**Comment by wrongecho** [comment]
Worth noting we have a Wiki for docs now - https://wiki.itflow.org

**Comment by johnnyq** [comment]
closing this will be ongoing and most is complete
