### ISSUE TITLE
Date fields issue

### ISSUE THREAD

**Issue by Wikiphil** [itflow-org/itflow#295]
Hello,

When entrering manualy a date, year's part accepts 6 digits. We have to do right arrow to pass to month and day. 

![date](https://user-images.githubusercontent.com/84292480/149702277-b81b66ee-4af9-4732-ae25-058049b20336.png)

![date2](https://user-images.githubusercontent.com/84292480/149702420-e3819425-39fe-495f-9ed2-6599ecc8cfea.png)

Regards.

**Comment by johnnyq** [comment]
that is very strange mine is not that way. I have tried with Firefox and Chrome. What Browser are you using?

**Comment by Wikiphil** [comment]
I use Microsoft Edge (Chromium bases) most of the time, suppose to be like Chrome.

Same issue in Chrome.

I'm not able to log in with my Firefox. I'll check this out later today.

I can try from somewhere else.

**Comment by johnnyq** [comment]
it must be a locale issue for some reason Canada allow 6 digit years

**Comment by Wikiphil** [comment]
No, not sure about locale issue. I'll try on another environment. US with Edge US.  I let you know.

**Comment by Wikiphil** [comment]
I've tested on Windows Server 2019  with Edge latest version: same issue.

![20220122-date1](https://user-images.githubusercontent.com/84292480/150661234-38bd1716-dbbe-4946-8838-a7c08eab66a0.png)


Edge is configured en-US
![20220122-date2](https://user-images.githubusercontent.com/84292480/150661235-87b281ba-eec4-4d04-af2d-bf74be4f3458.png)


Windows is configured en-US too
![20220122-date3](https://user-images.githubusercontent.com/84292480/150661247-07754a06-fc3b-465c-87e4-a6c0ec117260.png)

**Comment by Wikiphil** [comment]
May be I have solution for this issue: CSS controled fields.

When there is no limit on the date fields, I'm able to enter 6 digits year

![20220122-date4](https://user-images.githubusercontent.com/84292480/150661345-583a16f5-cc82-4e8c-847a-68165093eafb.png)

If I put limit on it, it works as excepted.

![20220122-date5](https://user-images.githubusercontent.com/84292480/150661355-1a40239b-0c71-406a-9aeb-6c9d3ba2bef8.png)

Let me know what you do you think about this avenue.

**Comment by johnnyq** [comment]
that sounds like a plan, I will implement that. Im not quite sure whats different from my setup and yours, that may be causing this super weird but ill apply your fix thank you

**Comment by wrongecho** [comment]
I'm able to replicate this also. A bit of research shows this is due to the design of the HTML date field (there's a 4-character mask, but a 6-character limit).
![image](https://user-images.githubusercontent.com/32306651/208255008-2f8c9481-3a4f-4adf-a224-263ecdbe5e23.png)
