### ISSUE TITLE
Assets password displayed by default on Main Assets screen

### ISSUE THREAD

**Issue by Wikiphil** [itflow-org/itflow#306]
Should be great to hide this password too.

![20220119-assets-screen](https://user-images.githubusercontent.com/84292480/150265734-f883d57b-1d32-449e-981c-bdec327b41b9.png)

![20220119-assets-screen-password](https://user-images.githubusercontent.com/84292480/150265747-8cf013b0-0607-4c38-9974-21471948be49.png)

Thanks again.

**Comment by johnnyq** [comment]
ill nail this one out
