### ISSUE TITLE
Feature request: Temp Secure Self Destructing Links

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#315]
Basically the way this would work if you wanted to send a client a document under documentation or a password or the whole their whole IT documentation or whatever else. This can be done by creating a secure link to an email. It could self destruct after 30 mins and self destruct after viewed, The view would be logged.

**Comment by aftechro** [comment]
That`s a great idea! 
IT Glue has something similar Public url which can be enabled or disabled as needed, but the url stays there

**Comment by Wikiphil** [comment]
In the past, I used something called self-destruct-o

**Comment by wrongecho** [comment]
I've added this initial functionality for docs, logins & files.

![share-ui](https://user-images.githubusercontent.com/32306651/155028283-5aec2095-a0e4-4ae5-ac03-b3d77dcbe0d3.png)
![share_client](https://user-images.githubusercontent.com/32306651/155028276-9caabb5c-8b4e-42b2-935a-c876c31a0372.png)
