### ISSUE TITLE
Feature Request: Software for multiple Assets

### ISSUE THREAD

**Issue by Wikiphil** [itflow-org/itflow#317]
Hi,

From the moment, same software keys can be install on multiple computers. 
Example: Microsoft Windows Server "Datacenter". It's good to know which VM run the key! 

I don't know yet how to handle this. I think we can choose it from the asset and just display the assets under software instead of having the right to set it.

![software-box](https://user-images.githubusercontent.com/84292480/150622224-38352aa8-c1e5-442d-b3ef-bdddec740686.png)

**Comment by aftechro** [comment]
What IT Glue have is one login related to multiple assets/configurations/websites and so on
for instance, volume license login - pc1, pc2 and so one

so i would recommend to have the same, related items (for the login section) and/or embedded passwords (for assets section) - and choose from existing assets/passwords list 

Passwords - with related items
![image](https://user-images.githubusercontent.com/38830718/150656134-5aea4d56-a561-4749-8ee3-8d5fe29586ae.png)

Configurations with embedded passwords
![image](https://user-images.githubusercontent.com/38830718/150656214-381f76be-0854-4bb4-95fd-503a33f268dd.png)

**Comment by Wikiphil** [comment]
I agree! :-)

**Comment by johnnyq** [comment]
This was complete you can assign multiple devices or users to a software license
