### ISSUE TITLE
Feature request: Add asset IP to main view

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#336]
Feature request: Add asset IP to main view
Not sure what we'd need to take away to make room for this, but I think showing the IP might be more useful than the install date/serial?

Thoughts?

**Comment by johnnyq** [comment]
Im almost wondering if we should have a separate tab for edit for each entitycalled Details that its job is to only display the most crucial and critical information in a non form.

**Comment by wrongecho** [comment]
I'd totally forgotten about DHCP! Good point there.

I like the idea of a details popup with the key details and related items in a non-form format. Rather than a separate tab, maybe it should be the default? Like when you click on the name of an asset, that's what it shows. If you want to see more & edit, you can go action>edit?

**Comment by johnnyq** [comment]
Added
247c2b3a88a3c3c8b7892d544c5eb48f9291f350
