### ISSUE TITLE
Feature Request: Ticketing Dashboard

### ISSUE THREAD

**Issue by andrejtr** [itflow-org/itflow#351]
Hi there,

TANSS has a cool Dashboard, you can see all activities at a glance.

It would be pretty cool if you guys could implement it into ITFlow!

Image: https://ibb.co/kMjbwgN
Ticketing-Software im reffering to: https://www.tanss.de/en

**Comment by wrongecho** [comment]
Some great ideas to work off here, thank you!
Closing as a duplicate of #141.
