### ISSUE TITLE
API Integrations

### ISSUE THREAD

**Issue by athornfam2** [itflow-org/itflow#366]
Any way to integrate ITFlow into NinjaRMM, TacticalRMM or DattoRMM?

**Comment by wrongecho** [comment]
We now have several read API endpoints, for assets, tickets, contacts, etc. Still working on adding endpoints to create/modify/delete data. I think once the API is complete, we can look at trying to integrate with other tools APIs potentially.

What's your ideal use case for this? What would be useful to be integrated exactly?

**Comment by athornfam2** [comment]
Asset syncing and adding/removing customers when removed from the RMM... Integrate assets into automated invoicing for services...

**Comment by wrongecho** [comment]
Hey @athornfam2, I recently added some basic integration with MeshCentral.

For now, we're going to work on building our API out and making it as comprehensive as possible. This will allow a lot more flexibility for custom scripting. 
In terms of integration with a specific RMM, I don't think we're going to be at that stage for a while.

**Comment by wrongecho** [comment]
Had a chat with Johnny about this and for now at least, we're just going to stick to working on the API and hold off on any integrations. Trying to integrate with every RMM out there is going to be a huge undertaking. On balance, I think working on the API and providing some easily adaptable sample scripts is a better use of our time - at least at the moment. 

I've started a [repo](https://github.com/itflow-org/itflow-api-powershell) with some basic scripts and I'll keep adding to it as I find the time. If you do end up writing any scripts, feel free to commit them to the repo!
