### ISSUE TITLE
Feature request: Asset service history

### ISSUE THREAD

**Issue by aftechro** [itflow-org/itflow#384]
Would be nice to have the Asset service history to show on the ticket, so whoever taking a new ticket from same contact, would know what issues that asset had and what had be done so far 

![image](https://user-images.githubusercontent.com/38830718/155863398-9279c61d-4028-4366-8e83-0c00cbf6f7d8.png)

**Comment by wrongecho** [comment]
I like this idea! I think we'll need a new table called asset_services or something to track an asset id and the associated ticket/notes.

**Comment by johnnyq** [comment]
@wrongecho Ill take on this one.

For now i'm going to use the existing tables

ticket_asset_id and asset_id

The summary will be the ticket subject

So it will display like so Ticket Number (with a link)  - Date Ticket Opened - Ticket Subject when viewing asset service history log.
This will be viewableby clicking View Service History button under assets as well as ticket details asset section.

We can add to this later as we feel fit.

**Comment by johnnyq** [comment]
This has been added although we can ad more to it at later date.

Also im going to do the same for client contacts and add the ability to view ticket history on them as well.

**Comment by aftechro** [comment]
There`s a bug here. If you try to add another ticket and assign same asset, it wont show the asset under newly created ticket.
So we have to make sure, the asset wont be assigned only to one ticket, and can be displayed to all the new tickets.

**Comment by aftechro** [comment]
I recommend something else, but we will chat about that when we will have the chance.  Not exactly what i had in mind for the asset service history, but this modal can be used for related tickets instead:

![image](https://user-images.githubusercontent.com/38830718/156060031-63324ad1-c260-40b7-baac-27a8ff83872c.png)


Problem is that I dont know how to show all other related open/closed tickets of the user. ATM shows only one.

**Comment by aftechro** [comment]
I recommend something else, but we will chat about that when we will have the chance.  Not exactly what i had in mind for the asset service history, but this modal can be used for related tickets instead:

![image](https://user-images.githubusercontent.com/38830718/156060384-07eac2dc-d003-4f0c-801a-10ccd97beaea.png)


Problem is that I dont know how to show all other related open/closed tickets of the user. ATM shows only one.

**Comment by Wikiphil** [comment]
Hi, 
Asset Service History displays correct information today, but the links to access the old ticket refer all to the current ticket ID.

Reproduce in the demo environnement

https://demo.itflow.org/ticket.php?ticket_id=228
Click on Service History
click on any of the 2 links.

![image](https://user-images.githubusercontent.com/84292480/213344939-4f194965-cba8-45ba-bdcb-b3ddd8405e4e.png)

Ticket 7 should go to https://demo.itflow.org/ticket.php?ticket_id=227.

**Comment by wrongecho** [comment]
Hey @Wikiphil. Thanks for raising.

Looks like the hyperlink was pointing to the ticket you were on, not the one referenced in the service history. I've raised a PR to fix.

**Comment by wrongecho** [comment]
![Screenshot_20230206-002424.png](https://user-images.githubusercontent.com/32306651/216855522-7fc5ca21-130f-43d9-b9aa-c9c3b1c4c0bf.png)

This feature has been added and is functional!
