### ISSUE TITLE
Log action consistency

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#408]
Hey,

Just a little unimportant thing, but I think we should standardize log actions a little more..

When a ticket is created we log into type Ticket action `Create`, but when a ticket reply is added we log action as `Created`. There's probably a lot more examples.

Can we decide on whether we're going to use

- `Create` / `Created`
- `Modify` / `Modified`
- `Delete` / `Deleted` 

It looks like settings-user.php uses Created/Modified/Deleted to show icons, so we can standardize on those?

**Comment by johnnyq** [comment]
Yeah I never could decide which one to stick with

I have been working on switching everything to create instead of created same with modify and delete.
Ill do this today but I think that should be the standard.

**Comment by johnnyq** [comment]
5f451dceefcb34d906a70856d0ebda0acdca5414

**Comment by johnnyq** [comment]
Okay I did a few more, I don't think I missed anything
