### ISSUE TITLE
"Search all Things" does not search inside documents

### ISSUE THREAD

**Issue by lunarcontrol** [itflow-org/itflow#440]
**Describe the bug**
Not sure if this is a bug but the "search all things" feature doesn't search inside documents. This is really important for IT documentation since often keywords will be within the document.

**Can you reproduce this on the demo at demo.itflow.org**
Yes, tested on the demo site.

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
1. Write a document with specific text
2. Search for that text in the "search all things"
4. Document will not show up.

**Expected behavior**
The "search all things" should include the text of documents and ideally (more a feature request) show the context of the search result.

**Screenshots**
Search everything box (returns nothing):
![image](https://user-images.githubusercontent.com/5004460/162846789-cb307474-cd36-40d4-8135-f05b4eb3ec8e.png)

Document listing ("lorem" is in document):
![image](https://user-images.githubusercontent.com/5004460/162846868-ffabfbf1-3b09-46a0-9589-7c05e64b8fa3.png)

**Additional context**

**Comment by wrongecho** [comment]
Heyy @lunarcontrol - This should now be resolved! Thanks again for letting us know about this.

![image](https://user-images.githubusercontent.com/32306651/163732536-328a1327-de1f-4962-91c7-6554c874565b.png)


Showing the context of the search [seems possible](https://stackoverflow.com/a/5188641), so is something we can look into more at a later date, should there be more interest.

**Comment by lunarcontrol** [comment]
Awesome ❤ 🙌

That's amazing! Thanks for adding this!!
