### ISSUE TITLE
Logins Work perfectly locally, but not over VPN. Possibly due to delay?

### ISSUE THREAD

**Issue by bitjbullock** [itflow-org/itflow#446]
**Describe the bug**
When I remote into my network via the terminal server and access ITflow there, any browser works fine and i can login. When I login from any browser on my home PC I'm presented with the login.php, i submit the login details and it reloads to login.php. Possibly a timeout? 

**Can you reproduce this on the demo at demo.itflow.org**
No.

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
See above.
We're using a 500/500 fiber connection, VPN is facilitated by a Watchguard M370. No other applications have this issue

**Expected behavior**
Login

**Screenshots**

**Additional context**

**Comment by wrongecho** [comment]
Hey @bitjbullock.

To be honest, this sounds like something unique to your setup. 

The only things I can think of at the moment are:
- check you're using HTTPS to connect (as ITFlow will not give you the cookies by default using HTTP only)
- does ITFlow register a successful login in the logs for this attempt over the VPN?
- check your Apache access/error logs
- proxying your traffic with something like Burpsuite so you can see exactly what is being sent/received.

**Comment by johnnyq** [comment]
@bitjbullock This really does sound related to what @wrongecho was saying about the cookies since the login page is redirecting you back to login.php this shows a session is not being set.

If you want to connect to it via http edit config.php
change:
`$config_https_only = TRUE; `

to

`$config_https_only = FALSE;`

this configuration should be okay as long as its behind a VPN and on a secure network.

**Comment by johnnyq** [comment]
Hello @bitjbullock did this resolve the login issue?

**Comment by bitjbullock** [comment]
I haven’t tried yet. But I will be.

Jonathan Bullock
Senior Systems Administrator
Office: 613 499 9960 Ext. 101
***@***.******@***.***>
www.Brock-IT.ca<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.brock-it.ca%2F&data=02%7C01%7CEnzoQ%40synnex.com%7Cc6f3f9fac39a4cb6771008d64fef6ac5%7C972a0e27c3554fd792259266c8f332ac%7C0%7C0%7C636784287089317214&sdata=GTCOpUxSN5BD1h1ryi%2Box58yNBDMco%2Fc1owLELy7ECA%3D&reserved=0>
[BIT-hires-logo]
This message is private and confidential. If you have received this message in error, please notify us and remove it from your system.
Please join us in making a positive impact on the environment. Think green. Read it on screen.
