### ISSUE TITLE
Client contacts table empty

### ISSUE THREAD

**Issue by aftechro** [itflow-org/itflow#458]
Hey guys,

Just got back from a long break and seen a lot of changes has been made.
I`ve downloaded the latest version of ITFlow and first, noticed that the Client Contacts tables is empty, even after the data is inserted . 

Was looking at errors below, couldn't figure it out where is the issue

2022/05/01 19:33:27 [error] 1101682#1101682: *251 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: contact_department in /home/myapp/public_html/client_overview.php on line 79PHP message: PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /home/myapp/public_html/client_overview.php on line 115PHP message: PHP Warning:  mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in /home/myapp/public_html/client_overview.php on line 138" while reading upstream, client: myip, server: mydomain, request: "GET /client.php?client_id=2&tab=overview HTTP/1.1", upstream: "fastcgi://127.0.0.1:8020", host: "mydomain", referrer: "https://mydomain/clients.php"
2022/05/01 19:33:29 [error] 1101682#1101682: *251 FastCGI sent in stderr: "PHP message: PHP Warning:  mysqli_fetch_array() expects parameter 1 to be mysqli_result, bool given in /home/myapp/public_html/client_contacts.php on line 83" while reading upstream, client: myip, server: mydomain, request: "GET /client.php?client_id=2&tab=contacts HTTP/1.1", upstream: "fastcgi://127.0.0.1:8020", host: "mydomain", referrer: "https://mydomain/client.php?client_id=2&tab=overview"

Have a second look please whenever you guys @wrongecho or @johnnyq have the chance.

Thank you!

**Comment by wrongecho** [comment]
Hey @aftechro, it's been a while!

The first two errors are related to you not having any expiring domains/asset warranties - nothing to worry about but we should tidy this up really.

I know Johnny moved departments to be part of the contacts table instead. That last error about client_contacts.php is complaining about the query for selecting all contacts. 
In Settings > Update, what's your database version? Does your contacts SQL table have a contact_department column?

**Comment by aftechro** [comment]
hey mate,

Current DB Version: 0.0.7

note that i changed the actually domain/subdomain with "mydomain" as well "myip" and "myapp" just to hide them from public view :D 

contact_department colum is there

**Comment by wrongecho** [comment]
Heyy!

That's fine, no worries :)

Is this a fresh install or an upgrade? I've just spotted an issue with `db.sql` that might cause this for fresh installs.

Could you do a structure-only export of your contacts table, please?

**Comment by aftechro** [comment]
Fresh install

Here is the contact table structure

![image](https://user-images.githubusercontent.com/38830718/166163402-404a27cf-b1bc-43fc-98a8-e386de956e26.png)

**Comment by aftechro** [comment]
Just FYA, running with mysql instead of mariadb, so i know some issues my occur because of that :D

**Comment by wrongecho** [comment]
Thanks for sending that over. Looks like you're missing `contact_department` due to the recent changes. This will also be broken for anyone that's installed in the last couple of days :(

I've raised #459 to correct. This should be fixed when you update your files & database (to 0.0.8).

Let me know if that fixes it?

**Comment by aftechro** [comment]
Works like a charm, Thank you, much appreciated!
