### ISSUE TITLE
Wrong Redirect URI sent to Azure for SSO

### ISSUE THREAD

**Issue by asasin114** [itflow-org/itflow#461]
**Describe the bug**
Cannot login to client portal with Azure SSO due to the wrong URI being sent to Azure by IT Flow.

**Can you reproduce this on the demo at demo.itflow.org**
NA

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
Go to Client Portal and attempt to login with an account that has Azure Login permission.
Once the login process is complete you receive an error that the redirect URI is incorrect. 

**Screenshots**
![azure_sso_error](https://user-images.githubusercontent.com/417006/166978780-0ef2d45c-9303-4122-b818-3e3cf63c1513.png)

**Additional context**
Seems to be an additional '/' added to the URI before the 'portal/login_microsoft.php' section (example "https://itflow.domain.com//portal/login_microsoft.php")

**Comment by asasin114** [comment]
Please ignore. I made a mistake with my config.php file. This is resolved.

**Comment by wrongecho** [comment]
Hey @asasin114, glad you figured this out.

If there's anything in the docs we could improve or otherwise change to make things clearer, please let us know!

**Comment by johnnyq** [comment]
@wrongecho  and @asasin114 I think this may be an issue as the base_url is set during setup and it appends / at the end of a domain everytime. I'll submit a fix shortly.
