### ISSUE TITLE
Document View Page Edit Button

### ISSUE THREAD

**Issue by peanutyost** [itflow-org/itflow#466]
**Describe the bug**
The edit button on the document page view is dead.
**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**Screenshots**
![Capture](https://user-images.githubusercontent.com/24262822/169666452-e371c2cf-ca3f-4bbf-bfc2-336fb8c12d0c.PNG)

**Comment by johnnyq** [comment]
Dupe Closing #467
