### ISSUE TITLE
Document View Page Related

### ISSUE THREAD

**Issue by peanutyost** [itflow-org/itflow#467]
**Describe the bug**
Document View Page Related box showing random string

**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**Screenshots**
![Capture](https://user-images.githubusercontent.com/24262822/169666489-dffda19f-1752-4ac5-8875-19a2a72a8db7.PNG)

**Comment by aftechro** [comment]
Hey @peanutyost! Thank you for your interest in this project.

Please note that the document sections is still in the developing mode, for which some functions are note yet available. 
The lead dev ops @johnnyq and @wrongecho will notify us all when this will be completed. 

Till then, feel free to do as many tests as you can and open PR to inform the team about anything you came across! 



On behalf of the IT Flow team, thank you!

**Comment by johnnyq** [comment]
@peanutyost @aftechro is correct we are still in development phases of redesigning the document viewing process with relations, we just pushed out another update, closing this for now
