### ISSUE TITLE
Hallo !

### ISSUE THREAD

**Issue by newerit** [itflow-org/itflow#474]
Please discuss feature requests on the forum @ https://forum.itflow.org/t/features - Thanks :)

New feature requests here will be closed.

Hallo i am find the system of ticket and webchat integrated with de whatsapp an telgram and librenmsAPI

**Comment by johnnyq** [comment]
Hello, thank you for you interest in ITFlow im not sure if this is what your asking but if its integration with WhatsApp, telegram and LibrenmsAPI. We have no plans to implement integration with those applications. We plan to keep ITFlow as small and minimal as possible.
