### ISSUE TITLE
Integration with Datto RMM

### ISSUE THREAD

**Issue by bitjbullock** [itflow-org/itflow#475]
There's already an assets section, would be nice if we could setup Datto RMM and other RMM tools to populate that data automatically.

**Comment by aftechro** [comment]
Hey @bitjbullock, thank you for the interest in IT Flow.
I believe there`s in plan the integration with the Tactical RMM, that the lead devs @johnnyq and @wrongecho will complete at some stage, but that will be later on in the project.

Feel free to register to https://forum.itflow.org and add a Feature request in there please. 

On behalf of the ITFlow team, thank you!

**Comment by wrongecho** [comment]
Hey @bitjbullock, thanks for getting in touch.

There are so so many different tools/products we could integrate with, so the best way we've come up with so far is to provide [examples](https://github.com/itflow-org/itflow-api-powershell) of scripts that sync assets between the two services using their APIs. 
We don't yet have an example for Datto but it shouldn't be too difficult to add one in the future.

In terms of **direct** integration with Datto/Snipe/CW/Ninja/Tactical/[Insert your tool here], that's probably not going to happen. I feel it's far more productive of our time to write example scripts that show/allow you do basically do anything you like with ITFlow.

**Comment by bitjbullock** [comment]
Thank you for the scripts. That's really all I was looking for.
