### ISSUE TITLE
Can't Login after first time logging in

### ISSUE THREAD

**Issue by mmxpy** [itflow-org/itflow#476]
**Describe the bug**
I go to login but it just goes back to the login page every time, I notice if I use the wrong account it will tell me but when I use a valid account it says nothing
 
**Can you reproduce this on the demo at demo.itflow.org**
No

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
Go to the site and try to login

**Expected behavior**
being able to login with a valid admin account

**Screenshots**
Nothing to show but the login page

**Additional context**
Not that I know

**Comment by mmxpy** [comment]
Nevermind the fix was:

If you want to connect to it via http edit config.php
change:
$config_https_only = TRUE;

to

$config_https_only = FALSE;

since I am only running it on a local network with http only

**Comment by wrongecho** [comment]
Glad you managed to figure it out, @mmxpy! We assume the use of HTTPS and therefore enforce secure cookies unless you set that variable in config.php to false.
