### ISSUE TITLE
Passwords in Client Area

### ISSUE THREAD

**Issue by HollowCyberSec** [itflow-org/itflow#482]
When inserting a password with symbols in the password field or in the notes field, an error pops up saying access forbidden.

**Comment by jcpit** [comment]
I don't appear to have that issue. 
Could it be your Modsec/WAF rules on the server?

**Comment by johnnyq** [comment]
@HollowCyberSec and @jcpit Yes i'm not able to replicate either

**Comment by HollowCyberSec** [comment]
I'm running ModSecurity with OWASP Rule set. Nothing else causes issues except that. I'll keep verifying what could be.
