### ISSUE TITLE
Itflow indexed by google

### ISSUE THREAD

**Issue by HollowCyberSec** [itflow-org/itflow#484]
I noticed that my domain for ITflow is being indexed by google. Where could I add the noindex meta tag to stop google from crawling my page?

**Comment by wrongecho** [comment]
Hey @HollowCyberSec 

Included in ITFlow is a [robots.txt](https://github.com/itflow-org/itflow/blob/master/robots.txt) which seems to do the trick - you'll notice that demo.itflow.org isn't indexed by Google.

Is robots.txt accessible from your web server root directory?

**Comment by HollowCyberSec** [comment]
Hey @wrongecho 

I did see the robots.txt file, but I could still see my domain in a google search. I consulted Google's forum, which says to add the noindex meta tag. And yes, my robots.txt file is accessible from the root directory.

**Comment by wrongecho** [comment]
Ah, looking into this a little more, it [seems](https://developers.google.com/search/docs/advanced/crawling/block-indexing) that you also need to add a meta tag..

Not sure if we'd want this to be simply added to the codebase or made a configurable setting (some people might want their instances to be discoverable). I'll let Johnny comment on this.

**Comment by HollowCyberSec** [comment]
That's the same document I saw. Surprisingly I checked for the demo version of IT flow, and it does not appear on google search. Mine appears without a description but sends you directly to the page. I had to switch to a sub-domain for it not to appear until the crawler searches again.

**Comment by johnnyq** [comment]
robots.txt only protects pages within the root directory and ITFlow should absolutely live in a root directory and not as sub directory of a website which if Wordpress can potentially expose ITFlow if a flaw was discovered in Wordpress.
Best practice is really to keep ITFlow on its own VM in a subdoman

**Comment by johnnyq** [comment]
another thing you can do is modify the robots.txt file

Change


User-agent: *
Disallow: /

to

User-agent: *
Disallow: /Name-SubDirectory

**Comment by johnnyq** [comment]
This has been done
6f6d737e64775c0a1cbec00dd325c5e81a38ee39

Let us know if this worked @HollowCyberSec it ma`y take a few weeks for google to take it off
