### ISSUE TITLE
Add .xlsm file type to allowed files list to be uploaded

### ISSUE THREAD

**Issue by filippvl** [itflow-org/itflow#487]
Like the title says.

I'm unable to upload .xlsm file to Files

Thanks guys, this project is awesome!

**Comment by johnnyq** [comment]
Hi @filippvl Ill get his added today for you check soon for an update. Thank you for you interest in ITFlow

**Comment by johnnyq** [comment]
55567df92e16fb0051bbc386dac241b618667004

This should be added goahead and update and please test and let us know.

**Comment by filippvl** [comment]
Hey @johnnyq thanks for the quick update! I'm not really experienced with this but my app is missing app and database update and it says that it has latest version. Is there a way to manually update the version?

Here is the screenshot: 
![image](https://user-images.githubusercontent.com/62236658/190705446-933a9a3b-a1ae-487b-a8dd-aa648d28a1e6.png)

**Comment by filippvl** [comment]
It's still the same after clearing everything... If I upload the https://github.com/itflow-org/itflow/archive/refs/heads/master.zip will I lose all the data?

**Comment by johnnyq** [comment]
i think I may, make sure you have git installed on your host. The update function depends on it

**Comment by filippvl** [comment]
Oh, can't have it then... All I can do is upload, edit files and delete them

**Comment by johnnyq** [comment]
oh I see. You are on a shared webhost platform. I would recommend an Ubuntu VPS and use the install script or you could always ask your webhost provider to install git.

**Comment by filippvl** [comment]
I will send them an email to see if they're willing to install git, thanks!
In the meantime it's not a good idea to just overwrite the existing files with new version?

**Comment by johnnyq** [comment]
Actually that should be find just make sure you backup your existing install

**Comment by filippvl** [comment]
I'll do that now and get back to you here once I test xlsm file, thanks for all the help again!

**Comment by filippvl** [comment]
@johnnyq just to give you an update, everything is fine after overwriting current installation with the new version, and also xlsm upload works now. Thank you!

**Comment by johnnyq** [comment]
Super! sounds good @filippvl
