### ISSUE TITLE
Cron not always executing successfully

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#496]
**Describe the bug**
Noticed a few days here and there where Cron did not execute which caused recurring invoices for that day not to be sent.

**Can you reproduce this on the demo at demo.itflow.org**
N/A

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**

**Expected behavior**
Cron should execute properly and if it doesnt a log needs to be present currently the log writes to console and does not log to a file

**Additional context**
I believe this might be an issue where the SMTP server is not responding or timing out causing the script to error out and then ending execution during email sending sections such as recurring invoice and or invoice reminders

**Comment by johnnyq** [comment]
implemented the following cron to log errors to trace the problem

now=$(date +%Y-%m-%d) && php /var/www/itflow/cron.php >> /var/log/itflow_cron_log-${now}

will look at the log files if it fails to run

**Comment by johnnyq** [comment]
seems to break if it cant connect to the SMTP Server apparently it breaks the whole script. If it times out connecting to the mail server it should log it and the cron script should just continue on executing its other tasks

**Comment by wrongecho** [comment]
@johnnyq, did the recent mail-related updates (#523) fix this at all? Errors should be handled and logged now.

**Comment by johnnyq** [comment]
That seems to have did the trick @wrongecho 
Good Work! and thank you. Ill close this out
