### ISSUE TITLE
Events/Calendar Disappear when adding more than 2 events

### ISSUE THREAD

**Issue by filippvl** [itflow-org/itflow#498]
**Describe the bug**
When I add more than 2 events to calendar the page just goes blank and then I can't edit anything regarding events

**Can you reproduce this on the demo at demo.itflow.org**
I've just tested and it works as it should on demo

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
Clients/Client name/Events/New event

**Expected behavior**
To display all the events on the calendar

**Screenshots**
![image](https://user-images.githubusercontent.com/62236658/201988625-5e27cefc-2f13-4100-b84e-b6498638797c.png)

**Additional context**
Event page for other clients is showing

**Comment by johnnyq** [comment]
Hi @filippvl this should be fixed now with the latest update please let us know if this fixed the issue on your end
b6e540825f2d525b5cc66fad80ecf25b8163dc67

**Comment by wrongecho** [comment]
Closing as fixed. Please let us know if this isn't the case :)
