### ISSUE TITLE
Document Templates not working

### ISSUE THREAD

**Issue by AndyRaphael** [itflow-org/itflow#524]
**Describe the bug**
I have created a Global Template. I then try to add a new document and from the drop down chose "From Template". But then nothing happens.

**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
1. Create a Global Template and save it
2. Click New document and chose From Template
3. Nothing happens

**Expected behavior**
Should see a list of templates to chose from

**Additional context**
Where do you edit existing templates?

**Comment by wrongecho** [comment]
Heyy @AndyRaphael 

Thanks for getting in touch.

I suspect that Johnny has not quite yet finished adding templates - #313 - but I'll let him confirm.

**Comment by johnnyq** [comment]
@AndyRaphael @wrongecho is right I am still working on this feature I hope to have this completed soon so stay tuned

**Comment by wrongecho** [comment]
Closing as duplicate against #313. Feel free to subscribe to notifications on that issue so you'll get notified when this is added :)
