### ISSUE TITLE
Feature Request: Delete associated asset login entry if all fields are made blank from the edit asset modal

### ISSUE THREAD

**Issue by AndyRaphael** [itflow-org/itflow#525]
### Original title: Removing Asset login does not remove key icon

**Describe the bug**
After deleting a previous login from an asset, the key icon remains

**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
1. Delete a login from an asset by clearing out fields and saving
2. Asset list still shows icon for password

**Expected behavior**
The key icon should no longer be visible to indicate there is no login stored

**Comment by wrongecho** [comment]
Hey @AndyRaphael 

Good spot on this, thanks for reporting! I've been able to validate your report.

When you add login details for an asset, ITFlow actually adds a login to the logins table and then associates that login with your asset. 
When you blank out the login details, all you're actually doing is removing the username/password from the associated login entry - the login entry itself actually still exists. To complicate, a login entry can have more than just a username/password - it can hold an OTP, URL, and Notes. 
As a workaround for this, you should go into the logins tab and manually delete the login to stop the key icon from showing up.

--

For a real resolution, we should probably add some functionality that deletes the login if the following conditions are met:
- From the edit asset view, the login username/password is made blank; **and**
- The login entry itself holds no other information (otp/url/notes)

**Comment by AndyRaphael** [comment]
That makes sense and I hadn't even checked that. But confirmed, this method works.

**Comment by johnnyq** [comment]
@AndyRaphael We will be rewriting this function shortly instead of a 1 to 1 relationship it will be many to many relationship.
If you assign more than 2 logins to an asset it will duplicate the asset listings for each login assigned to it.
So as we know asset can have multiple logins for example an AD Server or a Mail server etc

**Comment by wrongecho** [comment]
Looks like this has been fixed - 493a91d50228be609ce15c5c0929d8e6cce22c1d

Thanks again for raising :)
