### ISSUE TITLE
Feature Request: Improve Telemetry

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#531]
I think we should improve telemetry to better understand how ITFlow is being used. This would be 100% opt-in only and only gather metadata.

**Why?**
- Knowing more about how people use ITFlow will help in prioritizing the development of features.
- It'd also be great if we could publish some of this aggregated telemetry on the website to help promote ITFlow 
  - e.g. _X MSPs use ITFlow_ or _ITFlow has helped support Y number of clients worldwide_.

**Currently:**
- We collect data only on installation (opt-in)
- We collect: Date/Time submitted, Company Name, City, State, Country, Currency, and user comments (all user supplied)

**I'd like to move into a more continuous collection model where we can periodically collect more metadata.** 
This would probably be easiest via cron.

**How it would work:**

- Add two new database fields in the `settings` table for company 1:
  - `telemetry_identifier` (varchar)
  - `telemetry_status` (0/1 - default 0/off)
- During installation, we generate the telemetry identifier - this is **completely random but unique** to this install
  - We'd generate this as part of the update process for existing installations and ask users to consider taking part via a one-time in app notification
- Users should be prompted whether they want to participate in telemetry - this sets the `telemetry_status` field to 1
- If opted in, we send across the install data we currently collect (including their comments) 
- When cron runs, there is an _X in X_ (e.g. 1 in 7) chance that the updated telemetry data (below) would be sent/updated
- Users have the ability to adjust the telemetry status anytime via settings

**Metadata to collect:**

The total number of:
- Companies -- It would be great to see if anyone is actually using the multiple-company feature
- Users -- What's the headcount of companies using ITFlow? Are we just hitting tiny/small MSPs, or some larger ones too?
- Clients -- Same reasoning as users
- API keys -- Is anyone even using the API currently?

The config settings for:
- smtp_config_host -- Are people using the email-sending functionality? (just if the field is empty or not - not the value)
- config_module_enable_itdoc -- Are people using the documentation functionality?
- config_module_enable_ticketing -- Are people using the ticketing functionality?
- config_module_enable_accounting -- Are people using the accounting functionality?

**Data we specifically wouldn't collect:**
- All data we'd continuously collect would just be metadata. **We'd never collect any identifiable data - any names, client emails, etc. without additional explicit consent**.
  - This would be either the number of entities (e.g. number of users), or the state of a setting (true/false, on/off). 
- Even though we would technically have the ability to tie the telemetry identifier to a specific IP address, we'd never record this in the database. This data would be automatically purged as logs on the telemetry instance are rotated.

**Comment by johnnyq** [comment]
It has begun

a854baaf61f99c5559954e8d504166335930f632

**Comment by johnnyq** [comment]
Closing this for now as, the bases for this are there. Will continue to improve moving forward

**Comment by wrongecho** [comment]
Looking great, thank you!
