### ISSUE TITLE
Feature Removal: Multi-Company feature

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#532]
Johnny and I have discussed this and feel that if you are operating more than 1 MSP (or need a place to dev/test), it probably makes more sense to set up a completely separate ITFlow instance.

https://forum.itflow.org/d/74-removing-the-multi-company-feature

**Comment by johnnyq** [comment]
This has been complete
48fe49cf778b34e34112bdbdde49a74f88e11322
