### ISSUE TITLE
Code Standards: Spacing

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#538]
We should decide on whether we're using 2 or 4 spaces, and enforce this consistently across the codebase. 
Also need to update the relevant docs.

**Edit: After further discussion we are going to follow the [PSR](https://www.php-fig.org/psr/psr-12) recommendation of 4 spaces. **

To-do: Convert all code/files to 4 spaces instead of 2

**Comment by johnnyq** [comment]
2 spaces for sure should be standard along with converting tabs to spaces
