### ISSUE TITLE
NOT SHOWING REVENUES IN EACH PARTICULAR MONTH

### ISSUE THREAD

**Issue by chandachewe10** [itflow-org/itflow#548]
So when you go under `Reports -> Income` to view the income summary, the revenues in each particular month are not shown except under the `Total` bottom row where they are added together with other incomes. This is because the code fetching the revenues in each particular month always picks an auto increment id . Check this code which picks the revenues in each particular month
`report_income_summary.php` on line 65:

` $sql_revenues = mysqli_query($mysqli,"SELECT SUM(revenue_amount) AS revenue_amount_for_month FROM revenues WHERE revenue_id = $category_id AND YEAR(revenue_date) = $year AND MONTH(revenue_date) = $month");`
The code looks for the id of  `revenue_id` instead of the  `revenue_category_id`. 

Can I push for a PR?

**Comment by johnnyq** [comment]
Nice find and fix!! Thanks @chandachewe10

**Comment by johnnyq** [comment]
Thank you for fixing closing this issue out
