### ISSUE TITLE
Feature Request: Email notifications on unusual logins

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#562]
As a tech/accountant/admin, if you log in from a new user agent and IP address, you should receive an email notification to let you know.

**Comment by johnnyq** [comment]
Along with Two-factor failures. This will let someone know that someone guessed their user and password but did not get past 2FA

**Comment by wrongecho** [comment]
- b9b0440186ea13687c5af0ed4a7dece37e151d8a
- cc6380f785a6f8ae95cfbfa0bcc86d99873f8739
- fe00c0df2b8237c8fca9a2993e8404ab9e5848c8
- 6f900269d7956fb0302b732735fa9830bb0de2c1
