### ISSUE TITLE
Bug: Calendar Event - New Event: Hours are incrementing by 6 instead of 1 for end date/time

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#567]
**Describe the bug**
When you input date and time under new event in the calendar section it should auto fill the end time a hour ahead, instead it seems to fill 6 hours ahead

**Can you reproduce this on the demo at demo.itflow.org**
Yes
**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes
**To Reproduce**
1. Go to calendar events
2. New Event
4. Input start date time

**Expected behavior**
Should only increment 1 hour

**Additional context**
Here is the code, which seems to be correct

```
<script>

    // Function - called when user leaves field (onblur)
    function updateIncrementEndTime() {

        // Get the start date
        let start = document.getElementById("event_add_start").value;

        // Create a date object
        let new_end = new Date(start);

        // Set the end date to 1 hr in the future
        new_end.setHours(new_end.getHours() + 1)

        // Get the date back as a string, with the milliseconds trimmed off
        new_end = new_end.toISOString().replace(/.\d+Z$/g, "");

        // Update the end date field
        document.getElementById("event_add_end").value = new_end;

    }

</script>

```

**Comment by wrongecho** [comment]
I can't reproduce this.. Is this another weird locale thing?
![Recording 2023-01-23 at 20 17 23](https://user-images.githubusercontent.com/32306651/214141138-f845e99f-25df-4aab-a2be-666e8e0b2d8a.gif)

**Comment by johnnyq** [comment]
@wrongecho I think its a timezone thing. We are Eastern Timezone so UTC - 5
For you being in Europe its UTC 0
So i believe that has something to do with it
