### ISSUE TITLE
Vendor table - inconsistent schema

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#576]
Hi @johnnyq ,

Doing some bug hunting/fixing this morning!

You updated the vendor table schema in 4b9ba0b3c187cd9da65403af06b28e8ca6e82ba8, adding the field `vendor_template_id` via the update script but this seemed to fail for some reason (the field doesn't exist on my dev install or the demo).

Whilst there have probably been lots of changes in between, the master db.sql file for new installs only references `vendor_template` whilst the code on [vendors.php](https://github.com/itflow-org/itflow/blob/master/vendors.php#L123) (and client_vendors.php) makes reference to `vendor_template_id`.

Maybe the best approach would be to issue a database update that drops `vendor_template` and adds `vendor_template_id`?

Could you please take a look when you get a moment?

Thanks :)

**Comment by johnnyq** [comment]
Hi @wrongecho Thank you for pointing that out. vendor_template_id was dropped and replaced with vendor_template. If its 0 then its not a template if its 1 then it is a template. I just have to remove vendor_template_id references in the code, ill go ahead and do that today

**Comment by johnnyq** [comment]
This should do it
542300a56b6460221c20d28a23afef97640dc31c

**Comment by johnnyq** [comment]
This should be good closing this
