### ISSUE TITLE
Bug: DB Update does not always show needing an update when there is one

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#582]
**Describe the bug**
Right after updating ITFlow, sometime shows theres no Database update even though there was one. A simple refresh of the screen will show that the DB has an update available
**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
1. Go to Settings
2. Click Update
3. Sometimes no DB update show even though there was one

**Expected behavior**
A clear and concise description of what you expected to happen, if not obvious.

**Screenshots**

**Additional context**
This may possibly be a client side caching issue or maybe its refreshing to quickly before it can read the new database_version.php file. maybe adding a php wait statement may fix this before redirection

**Comment by wrongecho** [comment]
58fe752bd91f156566c1a21db1fd760e8a3b22c7 may fix

**Comment by johnnyq** [comment]
This appears fixed closing this, the new timeout is set to 1 sec now and it seems to do the job.
