### ISSUE TITLE
Bug: PHP 8.1 deprecates passing null values to htmlentities, preg_replace, numfmt_format_currency, etc.

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#591]
PHP 8.1 has deprecated the ability to pass null parameters to htmlentities, preg_replace and other functions.

![Image](https://user-images.githubusercontent.com/32306651/215805985-cd1e3e39-89cd-4e45-8374-375cecf3c562.png)

- https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation
- https://stackoverflow.com/questions/71707325/migration-to-php-8-1-how-to-fix-deprecated-passing-null-to-parameter-error-r

**Comment by johnnyq** [comment]
Well that's a mess. Hmm I don't understand why php will not accept "NULL" values  when passing functions to them. I think PHP foundation should rethink this one. Theres no good reason for this.

**Comment by johnnyq** [comment]
impressive @bhopkins0 we have been trying to tackle this one for a long time now. The commit looks great we will be reeling it on in.. Great Work!!

**Comment by wrongecho** [comment]
Seems like @bhopkins0 fixed this with a custom function. Please re-open if this isn't fully fixed.
