### ISSUE TITLE
BUG: Dashboard - Income By Category calculating invoice amounts not payments to the invoice

### ISSUE THREAD

**Issue by johnnyq** [itflow-org/itflow#60]
Income By Category calculating invoice amounts not payments to the invoice

**Comment by johnnyq** [comment]
to better word this: Its calculating Invoice amounts that have been marked payed but doesn't account for partial payment amounts to an invoice.

**Comment by o-psi** [comment]
@johnnyq @wrongecho do we know if this is still an issue. I could not replicate.
