### ISSUE TITLE
Call to undefined function sanitizeInputI()

### ISSUE THREAD

**Issue by Heart1010** [itflow-org/itflow#639]
When editing my company and click save I get an error 500 - I think that last `I` in sanitizeInputI() is not correct?

https://github.com/itflow-org/itflow/blob/b2deebfa42c8edbef2ae2c1c2a133c1592b60a7d/post.php#L478

After changing sanitizeInputI() to sanitizeInput() the save still ends in an error 500 with the following errer:

```bash
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: strip_tags(): Argument #1 ($string) must be of type string, mysqli given in /home/ooo/web/helpdesk.ooo-ppp-qqq.de/public_html/functions.php:633\nStack trace:\n#0 /home/ooo/web/helpdesk.ooo-ppp-qqq.de/public_html/functions.php(633): strip_tags()\n#1 /home/ooo/web/helpdesk.ooo-ppp-qqq.de/public_html/post.php(478): sanitizeInput()\n#2 {main}\n  thrown in /home/ooo/web/helpdesk.ooo-ppp-qqq.de/public_html/functions.php on line 633', referer: https://helpdesk.ooo-ppp-qqq.de/companies.php
```

So L478 have to be changed to this?
```php
$existing_file_name = sanitizeInput($_POST['existing_file_name']); 
```

**Comment by johnnyq** [comment]
Hi @Heart1010 Thank you for the the bug report. We applied your fix! We have migrated to santizeInput function and may there may still be some errors left throughout the code. Let us know if you find anything else we really appreciate your help.
