### ISSUE TITLE
Undefined variable $config_ticket_client_general_notifications (cron.php)

### ISSUE THREAD

**Issue by Heart1010** [itflow-org/itflow#640]
I get the following error from cron.php

```bash
PHP Warning:  Undefined variable $config_ticket_client_general_notifications in /home/xy/web/xy.de/public_html/cron.php on line 263
```
https://github.com/itflow-org/itflow/blob/7445cf1910723fa46df82be6bda2cba2a1bd0173/cron.php#L33-L38

I think the following $var is missing?

```php
$config_ticket_client_general_notifications = $row['config_ticket_client_general_notifications'];
```

**Comment by johnnyq** [comment]
Fantastic @Heart1010 Keep up the great work man sending a fix now
