### ISSUE TITLE
rocket chat / chat system

### ISSUE THREAD

**Issue by EIT-AUS** [itflow-org/itflow#645]
rocket chat integration (there is php client that can be logged in to at the same time as the user/agent)
ref: https://packagist.org/packages/fab1en/rocket-chat-rest-client

**Comment by EIT-AUS** [comment]
It looks like easy integration but could be wrong https://adminlte.io/docs/3.0/components/direct-chat.html

**Comment by wrongecho** [comment]
Hey @EIT-AUS

Thanks for getting in touch. We already have an open feature request on the forum for some sort of live chat integration. I've added your suggestion & link to the post :) 

https://forum.itflow.org/d/108-feature-request-chat-channel/2

Thanks!
