### ISSUE TITLE
Missing features ?

### ISSUE THREAD

**Issue by Cyril-INDRA** [itflow-org/itflow#703]
Hello,

We have installed ITflow via apt install and it seems that some features are missing such as assets, password management, SSO connection, ...
Is there anything to activate?

Thank you for your help.

**Comment by wrongecho** [comment]
Hey @Cyril-INDRA

Have you used the demo at all? Most features will be accessible once you create and open a client under the main "Clients" menu.

Note that SSO is only for client contacts to login with, not agents.

**Comment by Cyril-INDRA** [comment]
Thanks for the quick feedback, I've just understood how it works, thank you!
