### ISSUE TITLE
Cannot import CSV to password/ logins

### ISSUE THREAD

**Issue by georgesuba** [itflow-org/itflow#704]
**Describe the bug**
Cannot import CSV created from example file downloaded from itflow. App complaining about bad column. Same happens when you export existing records from itflow and try to import back after deleting all records, same error.

**Can you reproduce this on the demo at demo.itflow.org**
Yes

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**
1. Go to 'any client, passwords'
2. Click on 'import csv'

**Expected behavior**
It should upload csv and import data to db

**Additional context**
Can create gif animation of problem if need it.

**Comment by davesmith87** [comment]
I've ran into this issue as well.  If you remove the "url" column and data from the CSV file it will work.

**Comment by johnnyq** [comment]
Thanks for reporting we have now fixed the issue in the latest update
