### ISSUE TITLE
Added password generator

### ISSUE THREAD

**Issue by itechlab01** [itflow-org/itflow#721]
Good morning,

Is it possible in the future to set up a password generator ?

cordialy 
![Capture d’écran 2023-09-20 161351](https://github.com/itflow-org/itflow/assets/132558061/e805f6f6-36b3-4e37-874f-cad0cc2ca202)

**Comment by itechlab01** [comment]
Yes indeed, but it often gives me the same password, or it's a bug for me

**Comment by wrongecho** [comment]
Yeah, it'll only generate a single password. The password it generates is calculated at the page load time, there's currently no functionality to have it do anything different, or be able to choose length or complexity, etc. 

If you'd like to request that as a feature, please raise it on the forum :)
