### ISSUE TITLE
Mail stuck in Queued

### ISSUE THREAD

**Issue by Mandrake700** [itflow-org/itflow#722]
**Describe the bug**
I have sent a couple of tickets to test, But it seems the mail are stuck in the queue, Is there a way of forcing the mail to be send?
I have updated the software to te latest build as well 

**Can you reproduce this on the demo at demo.itflow.org**
NA

**Are you on the latest available version of ITFlow, with an up-to-date database structure?**
Yes

**To Reproduce**

**Expected behavior**
Emails not sending and no attempts is maid to send the email  from the Que as the attempt counter is still at 0

**Screenshots**

**Additional context**

--

To privately discuss a security issue, please see https://github.com/itflow-org/itflow/security

**Comment by wrongecho** [comment]
Hey,

Could you please share your solution?
Presumably this was the Cron job not being setup?

Thanks!

**Comment by Mandrake700** [comment]
Hello
Yes you are Correct. I found the answer in the documentation.
Thank you for your reply.
