### ISSUE TITLE
Feature Request: Ability to re-order quote/invoice items

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#742]
Users should have the ability to re-order quote/invoice items. Ideally they are draggable.

Not currently possible as [each invoice item has a incrementing ID](https://github.com/itflow-org/itflow/blob/master/db.sql#L663), meaning items must be manually copied/pasted. 

Bit of a tricky one: One solution may be to add a sort/order column to allow specific items to be moved.

https://forum.itflow.org/d/365-sortabledraggable-quote-items

--

- [ ] Users have the ability to re-order/custom order quote/invoice line items

**Comment by o-psi** [comment]
@johnnyq @wrongecho Please see https://github.com/itflow-org/itflow/pull/762

**Comment by o-psi** [comment]
We can mark this off the list, yes?

**Comment by johnnyq** [comment]
Yup Marking it off right now Thanks =]
