### ISSUE TITLE
Email sending vs queuing wording

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#909]
Since we moved to the mail queue system, most of the app still says "Mail sent" instead of "Mail queued" in the user feedback message. 

As per TCK-17, this is misleading and confusing. 
At the very least, the SMTP test page should say "Mail queued" and make reference to the Mail Queue. Ideally, all wording should be updated to reflect when messages are queued.

**Comment by johnnyq** [comment]
Updated the last of mail sent to mail queued and added and make the Admin > Mail Queue a clickable link

845e1689429918d26e46d582e9ae98a55a9bcee3
