### ISSUE TITLE
Feature Request: Custom Fields - Tickets - Ticket Status

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#925]
Some thoughts on how to allow users to add and use custom ticket statuses...

--

New table `ticket_statuses`
- ticket_status_id - int
- ticket_status_name - varchar for the name
- ticket_status_color - color for the ticket status (bootstrap: primary, success, danger, dark)
- ticket_status_active - 0/1, default 1 / active & visible
_Possibly add extra fields in future to allow for SLA pausing, etc_

Existing table `tickets`
- ticket_id
- [...]
- ticket_status - Use the ticket_status_id here

Functions
- Will also need to adjust functions.php - `getTicketStatusColor()` to allow looking up the correct colour
- Possibly add a custom function to automatically lookup the ticket status rather than having to add a join everywhere? `getTicketStatusName()` ?

**Comment by marnel007** [comment]
This is the one thing holding us back from moving to ITFLOW, We have build our own statues code,  It would be nice..

![image](https://github.com/itflow-org/itflow/assets/61925531/cff2e0cd-a061-47b7-a3ee-e65cecaff479)

**Comment by wrongecho** [comment]
Hey @marnel007 
Custom ticket statuses are literally just around the corner!

**Comment by marnel007** [comment]
Can you tell me how "around the corner"  week / month / days ....

**Comment by johnnyq** [comment]
days

**Comment by marnel007** [comment]
Bug in picking colors 

![image](https://github.com/itflow-org/itflow/assets/61925531/aff3b6d8-940f-4e5f-a7eb-0a00270d65ba)

**Comment by johnnyq** [comment]
Hey @marnel007 almost there this will be complete by end of today

**Comment by johnnyq** [comment]
Closing as this is completed

**Comment by marnel007** [comment]
Thank you !!
