### ISSUE TITLE
Feature Request: Client contacts ticket notification outside of original ticket creation flow

### ISSUE THREAD

**Issue by wrongecho** [itflow-org/itflow#937]
_Related to support req TCK-20._

If a ticket is created with nobody as the contact, or the contact/company is changed, then the new contact is never notified the ticket exists.
We need a way to email the latest contact of a ticket the original "New ticket raised" email - either intelligent logic when the contact is changed or a button to manually send the email.

**Comment by compumatter** [comment]
Thank you for breathing life into it.  Appreciated!
