### ISSUE TITLE
Bug: Blank webpage upon submitting stripe payment

### ISSUE THREAD

**Issue by Brokenlink404** [itflow-org/itflow#941]
A customer informed me and i was able to reproduce the issue. But the webpage goes to an all white page after submitting the payment for an invoice. Stripe it requesting a response to a webhook as well. not sure if the two are connected.

**Comment by wrongecho** [comment]
Hey @Brokenlink404

Thanks for your note. We only use Github issues for roadmap work now. Please raise this via the forum including any relevant php error logs and we can check this.

Thanks!
